import { Restaurant, MenuItem, FlashDeal, SpendDashboard, Coupon } from '../types';

export const mockRestaurants: Restaurant[] = [
  {
    id: '1',
    name: 'Pizza Palace',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400',
    rating: 4.5,
    reviewCount: 234,
    deliveryTime: '25-35 min',
    deliveryFee: 40,
    cuisines: ['Pizza', 'Italian', 'Fast Food'],
    isOpen: true,
    minimumOrder: 200,
  },
  {
    id: '2',
    name: 'Biryani House',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
    rating: 4.7,
    reviewCount: 512,
    deliveryTime: '30-40 min',
    deliveryFee: 30,
    cuisines: ['Biryani', 'North Indian', 'Mughlai'],
    isOpen: true,
    isFlashDeal: true,
    flashDealDiscount: 20,
    minimumOrder: 150,
  },
  {
    id: '3',
    name: 'Burger Barn',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
    rating: 4.3,
    reviewCount: 189,
    deliveryTime: '20-30 min',
    deliveryFee: 35,
    cuisines: ['Burger', 'American', 'Fast Food'],
    isOpen: true,
    minimumOrder: 100,
  },
  {
    id: '4',
    name: 'Chinese Dragon',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400',
    rating: 4.4,
    reviewCount: 321,
    deliveryTime: '35-45 min',
    deliveryFee: 50,
    cuisines: ['Chinese', 'Asian', 'Noodles'],
    isOpen: true,
    minimumOrder: 250,
  },
  {
    id: '5',
    name: 'South Spice',
    image: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=400',
    rating: 4.6,
    reviewCount: 445,
    deliveryTime: '25-35 min',
    deliveryFee: 25,
    cuisines: ['South Indian', 'Dosa', 'Idli'],
    isOpen: true,
    minimumOrder: 150,
  },
  {
    id: '6',
    name: 'Sweet Tooth',
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=400',
    rating: 4.8,
    reviewCount: 678,
    deliveryTime: '20-30 min',
    deliveryFee: 30,
    cuisines: ['Desserts', 'Bakery', 'Ice Cream'],
    isOpen: true,
    minimumOrder: 100,
  },
];

export const mockMenuItems: Record<string, MenuItem[]> = {
  '1': [
    {
      id: 'm1',
      name: 'Margherita Pizza',
      description: 'Classic pizza with fresh tomatoes, mozzarella, and basil',
      price: 299,
      image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
      category: 'Veg Pizzas',
      isVeg: true,
      isCustomizable: true,
      isAvailable: true,
      popular: true,
      customizations: [
        {
          id: 'c1',
          name: 'Size',
          type: 'single',
          required: true,
          options: [
            { id: 's1', name: 'Medium', price: 0 },
            { id: 's2', name: 'Large', price: 100 },
          ],
        },
        {
          id: 'c2',
          name: 'Extra Toppings',
          type: 'multiple',
          required: false,
          maxSelect: 5,
          options: [
            { id: 't1', name: 'Extra Cheese', price: 50 },
            { id: 't2', name: 'Mushrooms', price: 30 },
            { id: 't3', name: 'Olives', price: 25 },
          ],
        },
      ],
    },
    {
      id: 'm2',
      name: 'Pepperoni Pizza',
      description: 'Loaded with pepperoni and extra cheese',
      price: 399,
      image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400',
      category: 'Non-Veg Pizzas',
      isVeg: false,
      isCustomizable: true,
      isAvailable: true,
      popular: true,
    },
    {
      id: 'm3',
      name: 'Garlic Bread',
      description: 'Crispy garlic bread with butter and herbs',
      price: 129,
      image: 'https://images.unsplash.com/photo-1619531040576-f9416740663b?w=400',
      category: 'Sides',
      isVeg: true,
      isCustomizable: false,
      isAvailable: true,
    },
    {
      id: 'm4',
      name: 'Pasta Alfredo',
      description: 'Creamy alfredo sauce with pasta',
      price: 249,
      image: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=400',
      category: 'Pasta',
      isVeg: true,
      isCustomizable: true,
      isAvailable: true,
    },
  ],
  '2': [
    {
      id: 'm5',
      name: 'Hyderabadi Biryani',
      description: 'Authentic Hyderabadi dum biryani with aromatic spices',
      price: 299,
      image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
      category: 'Biryani',
      isVeg: false,
      isCustomizable: true,
      isAvailable: true,
      popular: true,
      customizations: [
        {
          id: 'c3',
          name: 'Portion',
          type: 'single',
          required: true,
          options: [
            { id: 'p1', name: 'Full', price: 0 },
            { id: 'p2', name: 'Half', price: -150 },
          ],
        },
      ],
    },
    {
      id: 'm6',
      name: 'Chicken 65',
      description: 'Spicy deep-fried chicken appetizer',
      price: 229,
      image: 'https://images.unsplash.com/photo-1610057099431-d73a1c9d2f2f?w=400',
      category: 'Starters',
      isVeg: false,
      isCustomizable: false,
      isAvailable: true,
      popular: true,
    },
    {
      id: 'm7',
      name: 'Dal Makhani',
      description: 'Creamy black lentils slow-cooked overnight',
      price: 189,
      image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
      category: 'Curry',
      isVeg: true,
      isCustomizable: false,
      isAvailable: true,
    },
  ],
  '3': [
    {
      id: 'm8',
      name: 'Classic Cheeseburger',
      description: 'Juicy beef patty with melted cheddar cheese',
      price: 199,
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
      category: 'Burgers',
      isVeg: false,
      isCustomizable: true,
      isAvailable: true,
      popular: true,
    },
    {
      id: 'm9',
      name: 'Veggie Burger',
      description: 'Plant-based patty with fresh vegetables',
      price: 179,
      image: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=400',
      category: 'Burgers',
      isVeg: true,
      isCustomizable: true,
      isAvailable: true,
    },
  ],
};

export const mockFlashDeals: FlashDeal[] = [
  {
    id: 'fd1',
    restaurantId: '2',
    restaurantName: 'Biryani House',
    restaurantImage: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
    discount: 20,
    itemNames: ['Hyderabadi Biryani', 'Chicken 65'],
    expiresAt: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
    isAvailable: true,
  },
  {
    id: 'fd2',
    restaurantId: '1',
    restaurantName: 'Pizza Palace',
    restaurantImage: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400',
    discount: 15,
    itemNames: ['Margherita Pizza', 'Garlic Bread'],
    expiresAt: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
    isAvailable: true,
  },
];

export const mockCoupons: Coupon[] = [
  {
    id: 'cp1',
    code: 'WELCOME50',
    description: 'Flat ₹50 off on your first order',
    discountType: 'flat',
    discountValue: 50,
    minimumOrder: 200,
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    isActive: true,
  },
  {
    id: 'cp2',
    code: 'FOODIE20',
    description: '20% off up to ₹100',
    discountType: 'percentage',
    discountValue: 20,
    minimumOrder: 300,
    maximumDiscount: 100,
    expiresAt: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    isActive: true,
  },
];

export const mockSpendDashboard: SpendDashboard = {
  monthlySpend: 4520,
  totalOrders: 12,
  topCuisines: [
    { name: 'Biryani', count: 4 },
    { name: 'Pizza', count: 3 },
    { name: 'Burger', count: 2 },
    { name: 'Chinese', count: 2 },
    { name: 'Desserts', count: 1 },
  ],
  totalSavings: 680,
  caloriesApprox: 24500,
};

export const getMenuByRestaurantId = (restaurantId: string): MenuItem[] => {
  return mockMenuItems[restaurantId] || [];
};


