apiVersion: v1
kind: ConfigMap
metadata:
  name: foodiego-backend-config
  namespace: foodiego
data:
  NODE_ENV: "production"
  API_PREFIX: "/api/v1"
  PORT: "4000"
  USE_POSTGRES: "true"
  MONITORING_EMIT_REQUEST_EVENTS: "true"
