apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../k8s
  - secret.local.yaml
images:
  - name: ghcr.io/foodiego/backend
    newName: foodiego/backend
    newTag: local
patches:
  - target:
      kind: Deployment
      name: foodiego-backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/command
        value:
          - node
      - op: add
        path: /spec/template/spec/containers/0/args
        value:
          - dist/server.js
